# Generated by Django 6.0.5 on 2026-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='商品编号')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('price', models.FloatField(default=0, verbose_name='商品单价')),
            ],
        ),
    ]
